# Setup
title:               Geonwoo Jo
tagline:             '일기장'
description:         '안녕하세요'
url:                 https://gunwbro.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Geonwoo Jo
  url:               https://github.com/gunwbro
  email:             gunwbro@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-146052-15

github:
  repo: https://github.com/gunwbro

linkedin:
  url: https://www.linkedin.com/in/gw00jo/

